#! /bin/sh
#
# auto_script.sh
# Copyright (C) 2018 qizai <jianhao2@illinois.edu>
#
# Distributed under terms of the MIT license.
#


./src/output full data/compressed_test/test_outfileArInt-0 data/ 100 1 &
./src/output full data/compressed_test/test_outfileArInt-0 data/ 100 100001 &
./src/output full data/compressed_test/test_outfileArInt-0 data/ 100 200001 &
./src/output full data/compressed_test/test_outfileArInt-0 data/ 100 300001 &

wait
echo "All complete."
